---
# task file for create MySQL DB and User
- name: create MySQL DB and User
  become: true
  hosts: '{{ ip_address | default("all") }}'
  
  tasks:
  
  # create MySQL database
  - name: create MySQL database
    mysql_db:
      login_password: "{{ mysql_root_password }}"
      name: "{{ bw_user }}_db"
      state: present
    
  - name: create user and assign to database
    mysql_user:
      login_password: "{{ mysql_root_password }}"
      name: "{{ bw_user }}"
      password: "{{ bw_password }}"
      priv: "{{ bw_user }}_db.*:ALL"
      state: present
      host: "{{ mysql_remote_host_ip }}"
      
      